Import('env', 'PackerLayer')

PackerLayer(
    uses=['distros/debian', 'defaults/initial'],
    locals={
        'arch': 'amd64',
        'distro_version': '13.6.0',
        'distro_tag': 'DVD-1',
        'distro_media_type': 'iso-dvd',
        'iso_url_dir':
            'https://cdimage.${local.distro}.org/${local.distro}-cd/${local.distro_version}/${local.arch}/${local.distro_media_type}',
        'iso_url':
            '${local.iso_url_dir}/${local.distro}-${local.distro_version}-${local.arch}-${local.distro_tag}.iso',
        'iso_checksum': 'file:${local.iso_url_dir}/SHA256SUMS',
        'guest_os_type': 'Debian12_64',
    },
    builder={
        'boot_command': [
            '<esc><wait>',
            'auto <wait>',
            'preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>',
            'netcfg/get_hostname={{ .Name }} <wait>',
            'packer_url=http://{{ .HTTPIP }}:{{ .HTTPPort }} <wait>',
            'packer_username=${local.ssh_username} <wait>',
            '<enter><wait>',
        ],
        'http_content': {
            '/preseed.cfg': '${templatefile("http/preseed.cfg",local)}',
            '/late-command.sh': '${file("http/late-command.sh")}',
            '/authorized_keys': '${local.ssh_public_key}',
        },
    },
)
