Import('env', 'PackerLayer')

PackerLayer(
    locals={
        'ssh_username': 'ansible',
        'ssh_timeout': '2h',
        'ssh_port': 22,
    },
    builder={
        'ssh_port': '${local.ssh_port}',
        'ssh_agent_auth': True,
        'ssh_username': '${local.ssh_username}',
        'ssh_timeout': '${local.ssh_timeout}',
    },
)
