Import('env', 'PackerLocation')

PackerLocation(
    locals={
        'packager': 'virtualbox',
        'guest_additions_url': '/usr/share/virtualbox/VBoxGuestAdditions.iso',
        'cpus': 4,
        'memory': 8000,
    },
    images=[
        'debian-virtualbox',
        'worchestation-debian-virtualbox',
        'kali-virtualbox',
        'worchestation-kali-virtualbox',
    ],
)
