Import('env', 'PackerLayer')

PackerLayer(
    provisioners=[
        {
            'ansible': {
                'playbook_file': '../../${local.location}/${local.stage}/.ansible/collections/ansible_collections/vmutti/worchestation/playbooks/provision.yml',
                'user': '${local.ssh_username}',
                'host_alias': '${local.location}_${local.stage}_${local.target}',
                'inventory_directory': '${local.build_directory}',
                'extra_arguments': [
                    '-e',
                    'target_hosts=${local.location}_${local.stage}_${local.target}',
                    '-i',
                    '../inventory/',
                    '-i',
                    '../../${local.location}/${local.stage}/inventory/',
                ],
                'inventory_file_template': (
                    '${local.location}_${local.stage}_${local.worchestation_group_suffix}:\n'
                    '  hosts:\n'
                    '    {{.HostAlias}}:\n'
                    '      ansible_host: {{.Host}}\n'
                    '      ansible_port: {{.Port}}\n'
                    '      ansible_user: {{.User}}\n'
                ),
                'ansible_env_vars': [
                    'ANSIBLE_CONFIG=../../${local.location}/${local.stage}/ansible.cfg',
                ],
                'use_proxy': False,
            },
        },
    ],
)
