Import('env', 'PackerLayer')

PackerLayer(
    uses=['distros/kali', 'defaults/initial'],
    locals={
        'arch': 'amd64',
        'distro_version': '2026.2',
        'iso_url_dir': 'https://cdimage.${local.distro}.org/${local.distro}-${local.distro_version}',
        'iso_url': '${local.iso_url_dir}/${local.distro}-linux-${local.distro_version}-installer-${local.arch}.iso',
        'iso_checksum': 'file:${local.iso_url_dir}/SHA256SUMS',
        'guest_os_type': 'Debian12_64',
    },
    builder={
        'boot_command': [
            '<esc><wait>',
            'auto <wait>',
            'priority=critical <wait>',
            'language=en <wait>',
            'country=US <wait>',
            'locale=en_US <wait>',
            'keymap=us <wait>',
            'preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>',
            'netcfg/get_hostname={{ .Name }} <wait>',
            'packer_url=http://{{ .HTTPIP }}:{{ .HTTPPort }} <wait>',
            'packer_username=${local.ssh_username} <wait>',
            '<enter><wait>',
        ],
        'http_content': {
            '/preseed.cfg': '${templatefile("../../../../layers/distros/kali-initial/http/preseed.cfg",local)}',
            '/late-command.sh': '${file("../../../../layers/distros/kali-initial/http/late-command.sh")}',
            '/authorized_keys': '${local.ssh_public_key}',
        },
    },
)
